### ISSUE TITLE
router 문제

### ISSUE THREAD

**Issue by s-ryuri** [md2eoseo/se12-front#2]
link를 걸고 버튼을 눌러도 홈페이지로 넘어가지 않음

**Comment by md2eoseo** [comment]
관련 코드 파일 코멘트로 올려주실 수 있으신가요?

**Comment by NyaNyak** [comment]
라우터 경로 다시 설정해서 메인페이지 - 로그인화면 간 페이지 전환이 가능해졌습니다.
로그인 pull request에 수정된 코드 커밋해서 올릴게요

**Comment by s-ryuri** [comment]
와우.. 고생하셨습니다
