### ISSUE TITLE
상품판매 활성화/비활성화 관련 버그

### ISSUE THREAD

**Issue by NyaNyak** [md2eoseo/se12-front#25]
현재 활성화/비활성화 버튼을 누른 후 새로고침을 하지 않고 다른 메뉴(AdminMenu)로 이동 시, 상태가 적용이 되지 않는 문제점이 있는 것 같습니다.

**Comment by md2eoseo** [comment]
네. Admin 페이지에서 상품, 배너 활성화/비활성화 버튼을 누르면 DB 데이터 변경은 되지만 다른 메뉴를 갔다 왔을 때 최신 상태가 적용되지 않고 이전 상태로 변경되는 문제 확인했습니다. state 적용을 다른 방식으로 해야될 것 같은데, 한 번 알아보겠습니다.

**Comment by NyaNyak** [comment]
그럼 일단, 임시로 저장 버튼을 만들어서 강제로 새로고침하게 구현해볼까요?

**Comment by md2eoseo** [comment]
네 그것도 괜찮은 방법인 것 같습니다. 그러면 그렇게 고치고 이슈는 계속 열어서 다른 방법도 찾아보죠.

**Comment by md2eoseo** [comment]
https://github.com/md2eoseo/se12-front/commit/0b15ab9509e7d53516170e0ac3a6e2a260c9c988 커밋으로 이슈 해결했습니다.
활성화 여부 수정 시 바로 cache를 수정하여 해결했습니다.
임시로 추가한 새로고침 함수는 제거했습니다.
