### ISSUE TITLE
관리자모드 / 유저모드 오류 이슈 (구조적? 보안?)

### ISSUE THREAD

**Issue by ufshg** [md2eoseo/se12-front#26]
오류발생 조건이 이렇게 됩니다.

1. 관리자계정으로 접속하고, 관리자 메뉴를 열람합니다.
2. 로그아웃하면 메인 화면으로 나오고, 여기서 유저 계정으로 로그인을 해도되고, 안해도됩니다.
3. 브라우저 뒤로가기를 하면 관리자계정 아니어도 관리자 페이지 열람이 됩니다.
4. 만약 상품관리페이지를 마지막으로 열람했었다면 해당 페이지에서 상품에 관해 조작도 가능합니다.
    (예를 들어 판매상태 조작 등. 실제로 해봄)

**Comment by md2eoseo** [comment]
이건 최대한 빨리 해결해야겠네요.. 확인해보니 실제로 DB 내용 변경이 되지는 않고 state만 변경이 됩니다. 그래도 정보가 노출되는 문제이니 빨리 해결해야겠습니다.

**Comment by md2eoseo** [comment]
뒤로가도 Admin 페이지를 렌더링 할 수 없도록 수정했습니다.
앞으로 관리자만 접근할 수 있는 페이지는 AuthRoute를 이용해 페이지를 렌더링 해야합니다.
