### ISSUE TITLE
관리자페이지 상품 비활성화 오류입니다.

### ISSUE THREAD

**Issue by ufshg** [md2eoseo/se12-front#30]
관리자 페이지에서 상품 비활성화를 누르고 저장을 하면

관리자 모드인데 목록에서 해당 상품이 없어집니다(...)

**Comment by md2eoseo** [comment]
additem 브랜치를 main에 merge 했습니다. 한 번 다시 확인해보시겠어요?

**Comment by ufshg** [comment]
사라진 상품들 다시 나타납니다!! 근데 또 오류를 발견했습니다...
가로로 길쭉한 사진을 아무거나 업로드했더니 css가 깨져버렸습니다.
추가로 책 제목을 너무 길게해버렸더니 상품 관리목록 박스  글씨배치가 깨져버려서...
뮤테이션으로 updateItem써서 수정해보려고 했는데 관리자 아니어서 접근도 안됩니다!

**Comment by md2eoseo** [comment]
네 이 부분은 css 수정이 필요하고요
뮤테이션으로 updateItem 쓸 때는 관리자 계정으로 해야되는데 아래 쪽에 관리자 토큰을 직접 복붙해서 넣어줘야 테스트할 수 있습니다.
login 뮤테이션으로 token 값 받아서 사용하시면 돼요.

**Comment by ufshg** [comment]
token 사용법 알아내서 일단 해당 데이터들 수정하였고, img 없는 item들에 img주소 적당히 넣어주었습니다
