### ISSUE TITLE
User 데이터필드 추가사항 및 장바구니 관련

### ISSUE THREAD

**Issue by NyaNyak** [md2eoseo/se12-front#32]
장바구니 기능을 구현하기위해 데이터항목을 추가할 필요가 있어보입니다.
로그인 상태에서만 장바구니를 사용할 수 있도록 간단한 코드를 짜보았는데, 비회원도 사용 가능한 것 보단
아무래도 이 편이 좀 더 관리하기 편할까요?

![image](https://user-images.githubusercontent.com/81071456/119260022-e6562700-bc0b-11eb-927d-ebf31abf81f4.png)

**Comment by md2eoseo** [comment]
백엔드에서 User 모델에 장바구니 기능을 추가해야될 것 같습니다. 추가하고 사용 방법을 따로 올려볼게요.
비회원은 localStroage를 이용하고 로그인한 회원은 해당 유저의 장바구니 필드에 상품 아이디를 추가하는 방법이 좋을 것 같습니다.

**Comment by md2eoseo** [comment]
`User`에 장바구니 필드인 `bag`를 추가했습니다.
`bag` 필드에 배열로 들어가는 BagItem 모델도 생성했습니다.
