### ISSUE TITLE
배너 등록시 공지/이벤트 선택부분 관련 이슈

### ISSUE THREAD

**Issue by ufshg** [md2eoseo/se12-front#35]
배너 등록시에 필수 입력사항들(배너이름, 이미지, 등록 기한 등)은 미입력시 필수 기입사항이라고 메시지를 띄워줍니다.

공지/이벤트 선택부분은 radio 로 구현이 되어있는데, 기본 선택은 공지로 되어있습니다.
그래서 "아 공지로 선택되었구나" 하고 나머지 채워서 등록을 하려하는 경우
최초 1회 무조건 공지/이벤트 여부를 선택하라고 메시지를 띄웁니다.
이후 다시 누르면 그냥 이상없이 공지로 선택된 채로 등록이 됩니다.

최초 상태가 공지임을 인식하지 못하는건지... 그래서 이슈 등록합니다.

**Comment by md2eoseo** [comment]
`react-hook-form`의 `setValue`로 해결했습니다.
