### ISSUE TITLE
회원가입폼 입력요소에 관하여

### ISSUE THREAD

**Issue by NyaNyak** [md2eoseo/se12-front#4]
1. 일단 필수 항목으로  ID, 이름, PW, 이메일주소가 들어가는게 맞는 것 같습니다. (제가 올렸던 코드에는 이메일 input 박스 
    placeholder에 선택입력이라고 쓰여있는데 이 부분은 수정하겠습니다.) 

2. 프론트팀이 개발을 진행하며 논의한 사항은 다음과 같습니다. 의견 남겨주시면 참고하여 수정하도록 하겠습니다.
   - 가입 시에는 주소를 입력하지 않고 이후에 주문할 때 따로 주소를 입력받아 회원 정보에 저장한다. 
   
3. 이외에 어떤 정보들이 더 들어가면 좋을지 논의가 필요해보입니다.

4. 현재까지 결정된 필수요소: ID, 이름, PW, 이메일주소, 전화번호

**Comment by s-ryuri** [comment]
그럼 지금 아이디 비밀번호, 비밀번호 재확인, 이름, 생년월일 성별, 이메일, 휴대전화를 만들기로 했는데 필수를 ID, 이름,PW, 이메일 주소말고 ID,이름,PW,핸드폰번호 이렇게 4가지로 하는건 어떨까요 사실 이메일 주소는 광고, 홍보 이메일 말고는 딱히 필요 없는 것 같아요 이메일 주소보단 핸드폰 번호가 더 필수인 것 같아요

**Comment by NyaNyak** [comment]
네! 저도 처음에 이메일을 선택으로 뺀 이유가 아무래도 전화번호보다는 사용되는 범위가 적다고 생각해서였거든요. 그런데 지금 요구사항pdf 다시 읽어보니까 이메일주소가 필수 정보로 들어가있네요..
저희가 지금 id를 이메일형식으로 받고 있는데, 이 부분에서도 수정이 필요할지 고민입니다.

**Comment by s-ryuri** [comment]
requirment pdf 확인해보니 그렇네요, 그럼 ID,PW,Email, 핸드폰 번호 5가지로 할까요, id는 아시다 싶이 사이트마다 좀 다르긴 한데이메일 사용 하는 경우도 좀 있어서 물론 아이디만 사용하는게 좀 더 많이 있긴 한 것 같아요, 그럼 이메일 형식 말고 아이디 형식으로 할까요? 보통 아이디를 더 많이 사용하니깐요,, 어차피 이 아아디 부분은 제가 구현해야되니,, 어떤 걸로 할 지 말씀해주세요

**Comment by NyaNyak** [comment]
아이디 중복체크와 이메일주소의 중복체크가 둘 다 들어가야하니까,
아이디 형식 그대로를 따르는게 좋을 것 같아요. 일단 지금 요소들까지 구현하고 추가해야 할 사항은 덧붙이는걸로 해요. 
아, 그리고 맡으신 부분 구현하실때 스타일은 신경 안쓰셔도돼요! 코드 넘겨주시면 제가 짜 놓은 디자인 그대로 적용해놓겠습니다.

**Comment by s-ryuri** [comment]
넵 확인 했습니다!

**Comment by NyaNyak** [comment]
의견 추가될 부분 고려해서 이 이슈는 그냥 열어두겠습니다!

**Comment by ufshg** [comment]
배송정보등으로 연계할 생각하면 핸드폰번호는 필요해보입니다. back쪽에 핸드폰번호 스키마 타입 추가 의견 전달해놓았습니다.

**Comment by md2eoseo** [comment]
SignUp 컴포넌트를 function component로 바꾸면서 react-hook-form 모듈도 적용했는데, 일단 User 데이터 모델에 정의한 필드 값들만 입력할 수 있게 form을 만들었습니다.(name, email, password, address) 나중에 추가적으로 필요한 정보가 있으면 그 때 form에 컴포넌트 추가하겠습니다.

**Comment by s-ryuri** [comment]
네 답글 확인했습니다
