### ISSUE TITLE
함수 구현 방식

### ISSUE THREAD

**Issue by s-ryuri** [md2eoseo/se12-front#5]
함수 구현 방식은 서로 달라도 상관 없겠죠?
꼭 똑같은 코드 스타일로 안하고 각자 방식으로 해도 상관 없을까요?

**Comment by NyaNyak** [comment]
각자 스타일로 구현한 다음에, 조금 더 나은 형태로 통합하는 과정이 필요할 것 같아요.
일단 구현 방식은 상관없을 것 같습니다!

**Comment by ufshg** [comment]
구현 -> 해당 코드 들고 논의 -> 선택 및 적용 이 좋아보여요!
