### ISSUE TITLE
apollo client 함수 function component에서만 사용 가능

### ISSUE THREAD

**Issue by md2eoseo** [md2eoseo/se12-front#7]
현재 몇몇 컴포넌트가 class component로 작성되어 있는데, apollo client 함수(useQuery나 useMutation)가 function component에서만 쓸 수 있다는 것을 알게 되었습니다. class component로 작성된 컴포넌트를 function component로 수정하는 작업 시작하겠습니다. 관련 질문사항 또는 개선 의견 있으시면 여기에 올려주세요.

**Comment by s-ryuri** [comment]
그럼 front에 있는 class component도 function으로 다 바꿔야되는건가요?

**Comment by md2eoseo** [comment]
네 function component로 통일하는게 좋을거같아요.
좀 이따 function component로 바꾼 Login 컴포넌트 커밋으로 올릴건데
그거 참고해서 다른 컴포넌트도 수정해야될 것 같아요.

**Comment by md2eoseo** [comment]
프로젝트 내에 class component가 더 이상 없으니 이 이슈는 닫겠습니다.
