### ISSUE TITLE
mege 취소

### ISSUE THREAD

**Issue by s-ryuri** [md2eoseo/se12-front#9]
브랜치 만들고 난 뒤에 pull request 요청하고
저 혼자 pull request 눌러봤는데
파일이 겹치는 문제가 발생하네요

그래서 merge를 취소 하려고
git reset --merge ORIG_HEAD
이 코드 쳐보고 하는데
어떻게 해야될까요?

**Comment by md2eoseo** [comment]
혹시 해결하셨나요? git pull, merge, reset을 하면서 커밋 히스토리가 많이 꼬이게 되면 프로젝트 폴더를 아예 지우고 다시 git clone 해보는 것도 좋을 것 같습니다. 그동안 작업한 내용을 커밋하지 않고 다른 곳에 복붙해 놓은 다음에 git clone 하면 됩니다. 정말 방법이 없을 때 이렇게 하면 시간 절약은 할 수 있어요.

**Comment by s-ryuri** [comment]
넵 팀원분이랑 얘기해서 해결했습니다. 말씀 해주신 방법도 참고하겠습니다.
